### ISSUE TITLE
IDE Can't resolve inherited methods on the helper classes

### ISSUE THREAD

**Issue by NathanLochala** [rmunate/LaravelHelpers#25]
There is no error in the code. 
It would be great if there were a way for PhpStorm to resolve the existing helper methods. Or, at least present in your documentation this limitation of the package. I might have chosen not to use it had I known. It's great though and I would like to continue to ue it. 
My IDE (PhpStorm 2024.1) shows an error in my code when I try something like:
```
<?php

namespace App;

use App\Helpers\Str;

class SomeClass
{
         public static function convertString($string): string
         {
                return Str::upper($string);       // <----- PhpStorm can't see the method 'upper' on the class Str and shows an error.
         }
}

**Comment by rmunate** [comment]
Hello, thank you for your comments. Based on your feedback, to ensure PhpStorm recognizes methods with reference to the class, it would be necessary to add something like this at the beginning of the `Str` class (in your example):

```php
/**
 * @method static string upper(string $value) Convert the given string to upper-case.
 */

class Str extends BaseHelpers
{
    use LaravelStrings;

    //...

}
```

Therefore, I have incorporated this into the stubs used for generating helper classes. I'll keep an eye out for any new comments or PRs from your side regarding further adjustments.

**Comment by NathanLochala** [comment]
Oh, nice fix, brother! I appreciate the clarification and the help. This will be hugely helpful.

**Comment by NathanLochala** [comment]
Still seems to be an issue. As you can see from my screenshot, the `use LaravelStrings;` already existed in my class. However, PhpStorm still can't recognize the inherited methods. 
<img width="724" alt="image" src="https://github.com/rmunate/LaravelHelpers/assets/168451730/b2a6df29-d9a7-4ab0-848f-1a6cf0275e8d">

**Comment by NathanLochala** [comment]
Oh, I see the comment that you are adding. It is a pity to have to write that in for each method we want to use, especially when we have to commit that to version control. Just isn't tidy. However, this is a great package and I appreciate your help.
